import ExcelJS from "exceljs";

export interface ExcelColumn {
  key: string;
  header: string;
  width: number;
  required?: boolean;
  auto?: boolean;
  numberFormat?: string;
  options?: string[];
}

interface WorkbookOptions {
  title: string;
  subtitle: string;
  fileName: string;
  sheetName: string;
  columns: ExcelColumn[];
  rows?: Record<string, unknown>[];
  template?: boolean;
}

export interface ImportedExcelRow {
  rowNumber: number;
  values: Record<string, unknown>;
}

const NAVY = "FF1A3458";
const TEAL = "FF0D7377";
const GOLD = "FFF5B942";
const PALE_BLUE = "FFEFF5FB";
const PALE_GRAY = "FFF3F4F6";
const BORDER = "FFD8DEE8";

function cellValue(value: ExcelJS.CellValue): unknown {
  if (value == null) return "";
  if (value instanceof Date) return value;
  if (typeof value !== "object") return value;
  if ("result" in value) return (value as ExcelJS.CellFormulaValue).result ?? "";
  if ("text" in value) return String((value as { text: unknown }).text ?? "");
  if ("richText" in value) {
    return (value as ExcelJS.CellRichTextValue).richText.map(part => part.text).join("");
  }
  return String(value);
}

function safeFileName(value: string) {
  return value.replace(/[\\/:*?"<>|]+/g, "-");
}

function download(buffer: ExcelJS.Buffer, fileName: string) {
  const bytes = new Uint8Array(buffer as ArrayBuffer);
  const blob = new Blob([bytes], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = safeFileName(fileName);
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function createExcelWorkbook({
  title,
  subtitle,
  fileName,
  sheetName,
  columns,
  rows = [],
  template = false,
}: WorkbookOptions): Promise<void> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Kiyometa Order Management";
  workbook.company = "Kiyometa";
  workbook.created = new Date();
  workbook.modified = new Date();

  const sheet = workbook.addWorksheet(sheetName.slice(0, 31), {
    views: [{ state: "frozen", ySplit: 5 }],
    pageSetup: {
      orientation: "landscape",
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
      paperSize: 9,
      margins: { left: 0.25, right: 0.25, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 },
    },
  });
  sheet.properties.defaultRowHeight = 20;
  sheet.mergeCells(1, 1, 1, columns.length);
  sheet.mergeCells(2, 1, 2, columns.length);
  sheet.mergeCells(3, 1, 3, columns.length);

  const titleCell = sheet.getCell("A1");
  titleCell.value = title;
  titleCell.font = { name: "Aptos Display", size: 20, bold: true, color: { argb: "FFFFFFFF" } };
  titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
  titleCell.alignment = { vertical: "middle" };
  sheet.getRow(1).height = 36;
  for (let column = 1; column <= columns.length; column += 1) {
    sheet.getCell(1, column).fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
  }

  sheet.getCell("A2").value = subtitle;
  sheet.getCell("A2").font = { name: "Aptos", size: 10, color: { argb: "FF52627A" } };
  sheet.getCell("A3").value = template
    ? "Fill one record per row. Columns marked AUTO are generated by the system and may be left blank."
    : `Exported ${new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date())}`;
  sheet.getCell("A3").font = { name: "Aptos", size: 9, italic: true, color: { argb: "FF7A8699" } };

  const headerRow = sheet.getRow(5);
  columns.forEach((column, index) => {
    const cell = headerRow.getCell(index + 1);
    cell.value = `${column.header}${column.required ? " *" : ""}${column.auto ? " (AUTO)" : ""}`;
    cell.font = { name: "Aptos", size: 10, bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: column.auto ? TEAL : NAVY } };
    cell.alignment = { vertical: "middle", wrapText: true };
    cell.border = { bottom: { style: "medium", color: { argb: GOLD } } };
    sheet.getColumn(index + 1).width = column.width;
  });
  headerRow.height = 28;

  const outputRows = template && rows.length === 0 ? [{}] : rows;
  outputRows.forEach((row, rowIndex) => {
    const excelRow = sheet.getRow(6 + rowIndex);
    columns.forEach((column, columnIndex) => {
      const cell = excelRow.getCell(columnIndex + 1);
      const value = row[column.key];
      cell.value = value instanceof Date ? value : (value ?? "") as ExcelJS.CellValue;
      cell.font = { name: "Aptos", size: 10, color: { argb: "FF243349" } };
      cell.alignment = { vertical: "middle", wrapText: true };
      cell.border = { bottom: { style: "hair", color: { argb: BORDER } } };
      if (column.auto) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: PALE_GRAY } };
        cell.font = { ...cell.font, color: { argb: "FF788397" }, italic: true };
      } else if (rowIndex % 2 === 1) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: PALE_BLUE } };
      }
      if (column.numberFormat) cell.numFmt = column.numberFormat;
    });
    excelRow.height = 24;
  });

  const validationEnd = Math.max(505, 5 + outputRows.length);
  columns.forEach((column, index) => {
    if (!column.options?.length) return;
    const formula = `"${column.options.join(",")}"`;
    for (let row = 6; row <= validationEnd; row += 1) {
      sheet.getCell(row, index + 1).dataValidation = {
        type: "list",
        allowBlank: !column.required,
        formulae: [formula],
        showErrorMessage: true,
        errorTitle: "Invalid value",
        error: `Choose one of: ${column.options.join(", ")}`,
      };
    }
  });
  sheet.autoFilter = { from: { row: 5, column: 1 }, to: { row: 5, column: columns.length } };
  sheet.headerFooter.oddFooter = "Kiyometa · &D · Page &P of &N";

  const instructions = workbook.addWorksheet("Instructions");
  instructions.columns = [{ width: 24 }, { width: 74 }];
  instructions.mergeCells("A1:B1");
  instructions.getCell("A1").value = "HOW TO USE THIS FILE";
  instructions.getCell("A1").font = { size: 18, bold: true, color: { argb: "FFFFFFFF" } };
  instructions.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
  instructions.getRow(1).height = 34;
  [
    ["Import", "Keep the first worksheet and its column headers unchanged, then upload the .xlsx file from the matching application tab."],
    ["Automatic numbers", "Leave AUTO columns blank for new records. Existing automatic numbers may be included to update a record, but cannot be changed."],
    ["Required values", "Headers marked with * must contain a value."],
    ["Dates", "Use an Excel date or YYYY-MM-DD."],
    ["Numbers", "Use numeric cells without unit text or currency symbols."],
    ["Safety", "Import validates references such as Item No and Product No before saving."],
  ].forEach((values, index) => {
    const row = instructions.getRow(index + 3);
    row.values = values;
    row.getCell(1).font = { bold: true, color: { argb: NAVY } };
    row.getCell(2).alignment = { wrapText: true, vertical: "top" };
    row.height = 34;
  });

  download(await workbook.xlsx.writeBuffer(), fileName);
}

function normalizedHeader(value: unknown) {
  return String(value ?? "")
    .replace(/\s*\*\s*$/, "")
    .replace(/\s*\(AUTO\)\s*$/i, "")
    .trim()
    .toLowerCase();
}

export async function readExcelRows(file: File, columns: ExcelColumn[]): Promise<ImportedExcelRow[]> {
  if (!file.name.toLowerCase().endsWith(".xlsx")) {
    throw new Error("Please choose an .xlsx Excel file.");
  }
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(await file.arrayBuffer());
  const sheet = workbook.worksheets[0];
  if (!sheet) throw new Error("The workbook does not contain a worksheet.");

  const expected = new Map(columns.map(column => [normalizedHeader(column.header), column]));
  let headerRowNumber = 0;
  const indexes = new Map<number, ExcelColumn>();
  for (let rowNumber = 1; rowNumber <= Math.min(sheet.rowCount, 20); rowNumber += 1) {
    const candidate = sheet.getRow(rowNumber);
    const candidateIndexes = new Map<number, ExcelColumn>();
    candidate.eachCell((cell, columnNumber) => {
      const column = expected.get(normalizedHeader(cellValue(cell.value)));
      if (column) candidateIndexes.set(columnNumber, column);
    });
    if (candidateIndexes.size >= Math.max(2, Math.ceil(columns.length / 2))) {
      headerRowNumber = rowNumber;
      candidateIndexes.forEach((column, columnNumber) => indexes.set(columnNumber, column));
      break;
    }
  }
  if (!headerRowNumber) {
    throw new Error("Excel headers do not match this tab. Download the template and keep its column names unchanged.");
  }

  const missing = columns.filter(column => column.required && ![...indexes.values()].some(found => found.key === column.key));
  if (missing.length) throw new Error(`Missing required column: ${missing.map(column => column.header).join(", ")}`);

  const result: ImportedExcelRow[] = [];
  for (let rowNumber = headerRowNumber + 1; rowNumber <= sheet.rowCount; rowNumber += 1) {
    const row = sheet.getRow(rowNumber);
    const values: Record<string, unknown> = {};
    let hasValue = false;
    indexes.forEach((column, columnNumber) => {
      const value = cellValue(row.getCell(columnNumber).value);
      values[column.key] = value;
      if (value !== "" && value != null) hasValue = true;
    });
    if (hasValue) result.push({ rowNumber, values });
  }
  return result;
}
